permalink: /posts/:title.html
timezone: Europe/London
exclude:
  - .forestry/
  - README.md
defaults:
  - scope:
      path: ''
      type: posts
    values:
      author: jdrydn
      excerpt_separator: <!--more-->
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: default

title: jdrydn

header:
  title: jdrydn
  image: /img/favicons/favicon-96x96.png
  links:
    - href: https://twitter.com/jdrydn
      text: Twitter
    - href: https://github.com/jdrydn
      text: GitHub
    - href: https://linkedin.com/in/jdrydn
      text: LinkedIn

author:
  name: James
  email: james@jdrydn.com
